### ISSUE TITLE
Travis changes

### ISSUE THREAD

**Issue by lukebigum** [LMAX-Exchange/puppet-linuxptp#3]
@gerhard-tinned I'm moving the discussion to an Issue, rather than a closed PR. You said in #2 that some of the recent Travis changes are causing you issues, what specifically? Is it latest commit 5fa1fed that wraps the sysconfig file in a Boolean?

**Comment by gerhard-tinned** [comment]
No the changes that cause problems for me are those, which are related to Travis itself. The one breaking Commit I identified so far is this one:

* bf6224260594a7e08ccad97ad6f38b139332eb77  test fixes - using rspec-puppet-facts gem, and combining class unit tests into one file

**Comment by lukebigum** [comment]
There aren't any changes to _.travis.yml_ in that commit, which is the config file for Travis.  There are Puppet RSpec changes though.  If that's what you mean then I'm going to need to see some sort of error message from your internal test system to figure out why it's not compatible.

**Comment by gerhard-tinned** [comment]
```
/usr/local/rvm/rubies/ruby-2.2.7/bin/ruby -I/usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/lib:/usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-support-3.5.0/lib /usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\{aliases,classes,defines,unit,functions,hosts,integration,type_aliases,types\}/\*\*/\*_spec.rb --color
/vagrant/modules/puppet-linuxptp_upstream/spec/spec_helper.rb:3:in `require': cannot load such file -- rspec-puppet-utils (LoadError)
        from /vagrant/modules/puppet-linuxptp_upstream/spec/spec_helper.rb:3:in `<top (required)>'
        from /vagrant/modules/puppet-linuxptp_upstream/spec/classes/linuxptp_spec.rb:1:in `require'
        from /vagrant/modules/puppet-linuxptp_upstream/spec/classes/linuxptp_spec.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
        from /usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
        from /usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
        from /usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
        from /usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
        from /usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
        from /usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
        from /usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'
/usr/local/rvm/rubies/ruby-2.2.7/bin/ruby -I/usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/lib:/usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-support-3.5.0/lib /usr/local/rvm/gems/ruby-2.2.7@puppet/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\{aliases,classes,defines,unit,functions,hosts,integration,type_aliases,types\}/\*\*/\*_spec.rb --color failed
```

**Comment by tosmi** [comment]
that's a problem with our internal vagrant puppet development box. there's just a gem missing.

@gerhard-tinned: let's look into that issue tomorrow, we just need to install the required gems.

toni

**Comment by lukebigum** [comment]
I'm going to assume from the two PRs I've got that this is not an issue for you any more.

**Comment by gerhard-tinned** [comment]
No, not yet. :-(
